/**
 * A curated list of 120 highly professional, field-agnostic motivational quotes
 * tailored for students, trainers, business owners, and aspiring specialists.
 * Each quote is strictly between 10 and 16 words.
 */
export const DAILY_QUOTES: string[] = [
  "Your dedication to building mastery shapes extraordinary opportunities. Keep moving forward.",
  "Great achievements are built on small, consistent steps of excellent daily practice.",
  "Focus on progress, refine your skills, and let consistency unlock your potential.",
  "Your continuous efforts today establish the foundation for tomorrow's professional success.",
  "Excellence is not an sudden event but a continuous habit of refined execution.",
  "Every intentional action you take brings you closer to your ultimate milestone.",
  "Believe in your vision, master your craft, and build with absolute persistence.",
  "Success is the natural compilation of daily focus and disciplined strategic progress.",
  "Refine your knowledge daily because small improvements compound into outstanding achievements.",
  "Your potential is unlocked when your daily preparation meets real-world opportunity.",
  "Shape your future through purposeful practice and unstoppable commitment to real growth.",
  "Consistency transforms average efforts into outstanding, career-defining professional accomplishments.",
  "The path to elite mastery belongs to those who show up every day.",
  "Craft your destiny through disciplined action, persistent focus, and high standards.",
  "Your willingness to learn is the strongest catalyst for your career acceleration.",
  "Build momentum through action and watch obstacles transform into rewarding career pathways.",
  "Success thrives where strong dedication meets continuous education and deliberate practice.",
  "Every milestone begins with the decision to try and the discipline to continue.",
  "Maintain your focus, elevate your standards, and trust the power of consistency.",
  "Nurture your expertise daily to stand out in a competitive global landscape.",
  "The secret of professional progress is simply getting started with what you have.",
  "Your aspirations require daily acts of courage, focus, and deliberate quality work.",
  "Stay focused under pressure because endurance defines the journey to global impact.",
  "Every daily exercise complete is another brick in your wall of achievements.",
  "Commit entirely to your standards and let outstanding quality speak for itself.",
  "Growth begins at the outer boundary of your current comfortable skill level.",
  "Your daily decisions determine your ultimate trajectory as an outstanding industry leader.",
  "Believe in the power of continuous learning to reshape your career possibilities.",
  "Transform raw passion into exceptional capability through focused and consistent study.",
  "The most secure path to leadership is the constant pursuit of deep expertise.",
  "Action fuels confidence, accelerates learning, and opens doors to elite worldwide careers.",
  "Keep your long-term goals clear while executing today's tasks with maximum accuracy.",
  "Excellence is a deliberate choice made in every single task you perform.",
  "Acknowledge your progress, adapt your strategies, and maintain an unstoppable forward drive.",
  "Your daily discipline represents the ultimate competitive advantage in any professional market.",
  "Great things happen when preparation meets relentless discipline and a positive orientation.",
  "True professional growth happens when you choose courage over easy routine tasks.",
  "Let your work ethic inspire others while constantly advancing your own capabilities.",
  "Your journey of self-improvement is the single best investment you will make.",
  "Build outstanding standards and let your reputation for quality open elite doors.",
  "The compound interest of daily learning is a highly powerful career multiplier.",
  "Approach every design challenge as a chance to demonstrate your refined capabilities.",
  "Stay curious, pursue exceptional quality, and let your professional integrity guide you.",
  "Small daily victories create the strong habits that secure your sustainable success.",
  "Your commitment to continuous learning is the most reliable path to authority.",
  "Strive for progress rather than perfection, and trust your ultimate career path.",
  "Focus your energy on what you can build and improve right now.",
  "Your professional trajectory is directly created by your daily commitment to excellence.",
  "Consistent discipline is the strong bridge between your aspirations and real accomplishments.",
  "Embrace challenges as valuable feedback loops that accelerate your practical skill development.",
  "True expertise is earned through focused, deliberate hours of high-quality targeted practice.",
  "Maintain high standards because early preparation leads to exceptional professional career triumphs.",
  "Your dedication today determines the level of impact you make in business.",
  "Every session of intentional study expands your horizon of global career opportunities.",
  "Success belongs to those who actively prepare for the future they desire.",
  "Turn professional challenges into stepping stones through strategic thinking and prompt execution.",
  "Keep refining your unique path with absolute clarity and unmatched daily persistence.",
  "Your talent gets you noticed, but absolute consistency secures your long-term success.",
  "The pursuit of knowledge is the ultimate foundation for enduring industrial influence.",
  "Show up with enthusiasm, practice with purpose, and build with reliable precision.",
  "Your daily output is a direct reflection of your inner drive for success.",
  "Excellence is the standard that separates aspiring amateurs from true industry leaders.",
  "Cultivate a resilient mindset and let your solid achievements speak for themselves.",
  "Every small breakthrough adds valuable momentum to your overall professional growth story.",
  "Focus on high-value activities that challenge your intellect and elevate your career.",
  "Success requires matching your strategic long-term vision with excellent immediate daily actions.",
  "Your work is a valuable contribution to the world. Keep building higher.",
  "Continuous improvement is the engine that drives your career to peak performance.",
  "Establish solid daily routines that prioritize your personal and professional skill development.",
  "Let your passion for quality set a new standard of industrial excellence.",
  "Stay true to your objectives, learn relentlessly, and rise above average expectations.",
  "Your commitment to quality craftsmanship defines your ultimate value in global markets.",
  "Be proactive, embrace strategic responsibility, and lead your projects with bold confidence.",
  "Every challenge contains a lesson that prepares you for high-responsibility leadership roles.",
  "Nurture your professional relationships and constant skill growth with equal dedication today.",
  "The best way to predict your career outcome is to actively create it.",
  "Your dedication to excellence inspires your peers and elevates the entire team.",
  "Success is built on a solid foundation of integrity, knowledge, and actions.",
  "Focus on mastering the fundamentals, and advanced opportunities will match your readiness.",
  "Every hurdle you cross builds the resilience needed for high-level global execution.",
  "Stay curious because an open mind is the ultimate source of innovation.",
  "Your daily effort is the direct catalyst for your upcoming career breakthrough.",
  "Work with purposeful intent and let your final results demonstrate your mastery.",
  "Consistency is the quiet fuel that powers long-term professional career transformation.",
  "Build your reputation on reliable delivery, exceptional quality, and constant skill progression.",
  "Your potential is a limitless resource that expands with every new challenge.",
  "Pursue mastery with clear focus and enjoy the rewarding process of growth.",
  "The discipline to finish what you start separates achievers from mere dreamers.",
  "Your daily learning is an irreplaceable asset that appreciates in value over time.",
  "Show up with intentional focus and let your performance establish new standards.",
  "Excellence is achieved when we consistently refuse to accept average quality work.",
  "Your strategic actions today ensure you remain highly relevant in tomorrow's market.",
  "Align your daily priorities with your ultimate objectives to construct lasting success.",
  "A commitment to daily improvement represents the ultimate blueprint for career longevity.",
  "Embrace constructive feedback as a gift that accelerates your journey toward mastery.",
  "Your unique combination of skills is highly valuable. Keep refining your craft.",
  "Success is an ongoing journey of learning, adapting, and continuously rising higher.",
  "Let your dedication to excellence shine through every direct client interaction today.",
  "Stay motivated by your long-term vision while remaining flexible in daily execution.",
  "Your consistent contribution is building a legacy of professional and personal achievement.",
  "Harness the power of focused attention to produce your finest work yet.",
  "Your dedication to lifelong learning guarantees your resilience in an industrial landscape.",
  "Every strategic choice you make either feeds your focus or starves it.",
  "Cultivate deep practical expertise because high capability is always in major demand.",
  "The standard you maintain in private determines your ultimate success in public.",
  "True innovators are defined by their continuous drive to learn and iterate.",
  "Your hard work is compounding in value hidden from immediate human sight.",
  "Set clear boundaries that protect your focus and amplify your overall output.",
  "Excellence is progress made visible through structured execution and endless curiosity.",
  "Your career is a masterpiece in development. Approach it with serious dedication.",
  "Success flourishes when you match your high ambition with continuous daily discipline.",
  "Be the expert who solves complex problems through elegant, reliable, professional solutions.",
  "Your focus determines your current reality. Keep it set on high achievements.",
  "Consistency is the ultimate difference between having an idea and making impact.",
  "Let your continuous thirst for learning be your constant professional competitive edge.",
  "Step into your power by committing to mastery in your chosen specialty.",
  "Your daily grit is the invisible foundation of your future public acclaim.",
  "A deliberate daily study plan keeps you ahead of changing industry trends.",
  "Excel today in the small items to prepare for tomorrow's massive responsibilities.",
  "Your persistent strive for excellence is the ultimate key to global prospects."
];

/**
 * Returns a deterministic quote from the list of 120 quotes based on the current day.
 * Ensures that all users (students, trainers, admins) see the exact same quote for a given date.
 */
export function getQuoteOfTheDay(): string {
  try {
    // Get time in UTC to avoid timezone differences between client browsers
    const now = new Date();
    const utcTime = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());
    const dayTimestamp = Math.floor(utcTime / (24 * 60 * 60 * 1000));
    
    // Day index modulo the number of quotes (120)
    const quoteIndex = Math.abs(dayTimestamp) % DAILY_QUOTES.length;
    return DAILY_QUOTES[quoteIndex];
  } catch (e) {
    return DAILY_QUOTES[0];
  }
}
