import { Curriculum } from './types';

export const INITIAL_CURRICULA: Curriculum[] = [
  {
    id: "c-1",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Full-Stack Software Engineering",
    description: "Students graduate as Full-Stack Developers capable of building, deploying, and maintaining responsive web applications from database architecture to smooth frontend user interfaces.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 16,
    modules: ["Week 1-4: Advanced UI Layouts & Spatial Typography", "Week 5-8: Server Logic & RESTful APIs (Node.js/Express)", "Week 9-12: Relational Databases & Schema Migrations", "Week 13-16: Cloud Deployment & Container Integration"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 550000,
    pricingBeginner: 350000,
    pricingIntermediate: 550000,
    pricingExpert: 800000,
    equipment: "8GB RAM Laptop (Minimum Core i5), stable internet, GitHub account.",
    outcomes: "Students graduate as Full-Stack Developers capable of building, deploying, and maintaining responsive web applications from database architecture to smooth frontend user interfaces."
  },
  {
    id: "c-2",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Frontend Web Development (React/Vue)",
    description: "Graduates become Frontend Engineers who convert UI mockups into interactive, high-performance web pages with smooth component states and API integrations.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 12,
    modules: ["Week 1-3: Javascript Mastery & ES6 Syntax", "Week 4-6: Dynamic React Architecture & Component Lifecycles", "Week 7-9: Client State & Complex Route Managers", "Week 10-12: High Performance Web Optimization & App Delivery"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 350000,
    pricingBeginner: 200000,
    pricingIntermediate: 350000,
    pricingExpert: 500000,
    equipment: "8GB RAM Laptop, VS Code, internet access.",
    outcomes: "Graduates become Frontend Engineers who convert UI mockups into interactive, high-performance web pages with smooth component states and API integrations."
  },
  {
    id: "c-3",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Backend Web Development (Node.js/Python)",
    description: "Students become Backend Engineers skilled in building fast APIs, managing user authentication pipelines, optimizing database models, and server logic.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 12,
    modules: ["Week 1-3: Server Architectures & Node.js/Python CORE", "Week 4-6: Structured API design & Bearer Token Authentication", "Week 7-9: Database Query optimization & Postgres/NoSQL", "Week 10-12: Micro-services communication & App Security"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 400000,
    pricingBeginner: 250000,
    pricingIntermediate: 400000,
    pricingExpert: 600000,
    equipment: "8GB RAM Laptop, Docker Desktop environment, Postman.",
    outcomes: "Students become Backend Engineers skilled in building fast APIs, managing user authentication pipelines, optimizing database models, and server logic."
  },
  {
    id: "c-4",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "UI/UX Product Design",
    description: "Graduates become Product Designers capable of running user research, mapping interactive wireframes, and creating high-fidelity Figma prototypes ready for developers.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 10,
    modules: ["Week 1-3: User Persona Creation & Spatial Grids", "Week 4-5: Interactive Wireframes & Low-Fidelity Mockups", "Week 6-8: Advanced Figma Prototyping & Design Systems", "Week 9-10: Client Delivery, Design Handoffs & Usability Audits"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 300000,
    pricingBeginner: 180000,
    pricingIntermediate: 300000,
    pricingExpert: 450000,
    equipment: "8GB RAM Laptop (Core i3+), Figma desktop client.",
    outcomes: "Graduates become Product Designers capable of running user research, mapping interactive wireframes, and creating high-fidelity Figma prototypes ready for developers."
  },
  {
    id: "c-5",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Data Analytics & Business Intelligence",
    description: "Students transform into Data Analysts who clean chaotic corporate datasets and build interactive executive dashboards to guide business strategy.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 10,
    modules: ["Week 1-3: Structured Datasets Cleaning & Excel Formulas", "Week 4-6: Relational Queries with SQL", "Week 7-8: Business Metrics Visualizations (Power BI/Tableau)", "Week 9-10: Predictive Indicators Analysis & Boardroom Presentation"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 300000,
    pricingBeginner: 150000,
    pricingIntermediate: 300000,
    pricingExpert: 500000,
    equipment: "8GB RAM Laptop, Microsoft Power BI or Tableau, Excel.",
    outcomes: "Students transform into Data Analysts who clean chaotic corporate datasets and build interactive executive dashboards to guide business strategy."
  },
  {
    id: "c-6",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Data Science & Machine Learning",
    description: "Graduates become Data Scientists capable of engineering predictive models, writing advanced Python algorithms, and automating operational data pipelines.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 14,
    modules: ["Week 1-3: Advanced Python Statistics & Jupyter Environments", "Week 4-6: Data wrangling (Pandas / NumPy)", "Week 7-10: Supervised ML & Regressors with Scikit-learn", "Week 11-14: Model Pipelines Deployment & Telemetry Integration"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 450000,
    pricingBeginner: 250000,
    pricingIntermediate: 450000,
    pricingExpert: 700000,
    equipment: "16GB RAM Laptop (or cloud-hosted Jupyter environments), Python environment.",
    outcomes: "Graduates become Data Scientists capable of engineering predictive models, writing advanced Python algorithms, and automating operational data pipelines."
  },
  {
    id: "c-7",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Advanced Cyber Security & Ethical Hacking",
    description: "Students graduate as Information Security Analysts who run systematic vulnerability scans, patch network flaws, and defend digital infrastructure against active exploits.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 12,
    modules: ["Week 1-3: Network Topologies Audits & Routing Protocols", "Week 4-6: Vulnerability Scans & Penetration Testing (Kali Linux)", "Week 7-9: App Sec & OWASP TOP 10 Remediation", "Week 10-12: Cryptographic Firewalls & Security Event Management"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 500000,
    pricingBeginner: 300000,
    pricingIntermediate: 500000,
    pricingExpert: 850000,
    equipment: "16GB RAM Laptop, Kali Linux virtual environment, testing sandbox.",
    outcomes: "Students graduate as Information Security Analysts who run systematic vulnerability scans, patch network flaws, and defend digital infrastructure against active exploits."
  },
  {
    id: "c-8",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Cloud Computing (AWS/DevOps)",
    description: "Graduates become DevOps Engineers capable of automating cloud infrastructure deployments, setting up continuous integration pipelines, and monitoring system uptimes.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 12,
    modules: ["Week 1-3: AWS Core Services (EC2, S3, IAM)", "Week 4-6: Infrastructure as Code (Terraform Layouts)", "Week 7-9: CI/CD Pipelines & Jenkins/GitHub Workflows", "Week 10-12: Kubernetes Cluster Orchestration & Load Testing"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 450000,
    pricingBeginner: 250000,
    pricingIntermediate: 450000,
    pricingExpert: 650000,
    equipment: "8GB RAM Laptop, active AWS/Azure free-tier sandbox.",
    outcomes: "Graduates become DevOps Engineers capable of automating cloud infrastructure deployments, setting up continuous integration pipelines, and monitoring system uptimes."
  },
  {
    id: "c-9",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Product Management",
    description: "Students transform into Tech Product Managers who run agile sprint boards, write comprehensive feature specs, and smoothly coordinate engineering and design workflows.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Product Roadmap Definition & Specifications Parsing", "Week 3-4: Running Agile Sprint Ceremonies with Jira", "Week 5-6: Design Handoffs Audits & Technical Coordination", "Week 7-8: Modern Product KPI Analytics & Conversion Optimizations"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 250000,
    pricingBeginner: 150000,
    pricingIntermediate: 250000,
    pricingExpert: 400000,
    equipment: "Laptop, Jira Software access, Miro or FigJam workspaces.",
    outcomes: "Students transform into Tech Product Managers who run agile sprint boards, write comprehensive feature specs, and smoothly coordinate engineering and design workflows."
  },
  {
    id: "c-10",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Direct-Response Copywriting",
    description: "Graduates become High-Ticket Copywriters who write high-converting landing pages, sales sequences, and ad copy that directly drives revenue for tech brands.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 6,
    modules: ["Week 1: Cognitive Pitch Models & Client Profiling", "Week 2-3: Landing Page Headlines & Multi-Tier Selling Angles", "Week 4-5: Creating Conversions-focused Email Series loops", "Week 6: High Ticket Pitches Drafting & Copywriting Client Capture"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 180000,
    pricingBeginner: 100000,
    pricingIntermediate: 180000,
    pricingExpert: 300000,
    equipment: "Any basic functional laptop or tablet, Google Docs.",
    outcomes: "Graduates become High-Ticket Copywriters who write high-converting landing pages, sales sequences, and ad copy that directly drives revenue for tech brands."
  },
  {
    id: "c-11",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Growth Marketing & Customer Acquisition",
    description: "Students become Growth Marketers capable of managing profitable ad budgets, building viral growth loops, and scaling user acquisition engines for products.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Marketing Funnels Setup & Attribution Trackings", "Week 3-4: Scaling ads budgets (Meta / Google Ads Accounts)", "Week 5-6: Viral Marketing loops installation", "Week 7-8: Client retention loops & cohort analysis"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 220000,
    pricingBeginner: 120000,
    pricingIntermediate: 220000,
    pricingExpert: 350000,
    equipment: "Laptop, active Meta/Google Ads Manager dashboard testing accounts.",
    outcomes: "Students become Growth Marketers capable of managing profitable ad budgets, building viral growth loops, and scaling user acquisition engines for products."
  },
  {
    id: "c-12",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Social Media Strategy & Content Creation",
    description: "Graduates become Social Media Managers capable of designing monthly organic content pillars, recording engaging shorts, and building loyal online communities.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 6,
    modules: ["Week 1-2: Organic Content Planning & Visual Calendars", "Week 3-4: Recording high-fidelity short videos on mobile devices", "Week 5: Captivating copy drafts & Capcut editing loops", "Week 6: Community moderation workflows & engagement strategies"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 120000,
    pricingBeginner: 70000,
    pricingIntermediate: 120000,
    pricingExpert: 200000,
    equipment: "Smartphone with a high-quality camera, ring light, CapCut mobile app.",
    outcomes: "Graduates become Social Media Managers capable of designing monthly organic content pillars, recording engaging shorts, and building loyal online communities."
  },
  {
    id: "c-13",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Search Engine Optimization (SEO) Mastery",
    description: "Students transform into SEO Specialists who audit technical site code, map profitable content networks, and rank business sites at the top of Google.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Core Keywords research & Competitors auditing", "Week 3-4: On-Page Optimization rules (Metadata, H1 Scales)", "Week 5-6: Technical SEO, indexing grids & Google Search Console", "Week 7-8: Link Building Campaigns & Content hubs formation"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 150000,
    pricingBeginner: 80000,
    pricingIntermediate: 150000,
    pricingExpert: 250000,
    equipment: "Laptop, access to SEO tools (such as SEMrush, Ahrefs, or Google Search Console).",
    outcomes: "Students transform into SEO Specialists who audit technical site code, map profitable content networks, and rank business sites at the top of Google."
  },
  {
    id: "c-14",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Mobile App Development (Flutter/React Native)",
    description: "Graduates become Mobile App Developers who compile clean, cross-platform Android and iOS applications from a single, high-performance codebase.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 14,
    modules: ["Week 1-4: Cross-Platform Paradigms & Dart/ES6 syntaxes", "Week 5-7: Mobile layout patterns, layouts systems & states", "Week 8-10: Native APIs access & local file stores", "Week 11-14: Play Store / App Store Deployments checklists"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 400000,
    pricingBeginner: 250000,
    pricingIntermediate: 400000,
    pricingExpert: 650000,
    equipment: "8GB-16GB RAM Laptop, Android Studio or Xcode frameworks.",
    outcomes: "Graduates become Mobile App Developers who compile clean, cross-platform Android and iOS applications from a single, high-performance codebase."
  },
  {
    id: "c-15",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "No-Code Automation & SaaS Architecture",
    description: "Students become Automation Consultants who design complex, lightning-fast business backend workflows and database systems using zero-code tools.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Airtable Relational Databases design", "Week 3-5: Automating triggers & actions (Make.com/n8n hubs)", "Week 6-7: Integrating Webhooks, APIs & Gmail pipelines", "Week 8: Client Delivery dashboards & SaaS prototypes mapping"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 200000,
    pricingBeginner: 120000,
    pricingIntermediate: 200000,
    pricingExpert: 350000,
    equipment: "Laptop, active testing sandboxes for Make.com, n8n, and Airtable.",
    outcomes: "Students become Automation Consultants who design complex, lightning-fast business backend workflows and database systems using zero-code tools."
  },
  {
    id: "c-16",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Technical Writing & Documentation",
    description: "Graduates become Technical Writers capable of translating complex backend code architectures into beautiful API documentations, developer user guides, and SDK manuals.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 6,
    modules: ["Week 1-2: Structured Technical Outlines & Markdown Mastery", "Week 3-4: Documenting REST APIs (OpenAPI / Swagger specifications)", "Week 5: Code walkthroughs generation & Quickstarts design", "Week 6: Static documentation deployment sites setup"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 160000,
    pricingBeginner: 90000,
    pricingIntermediate: 160000,
    pricingExpert: 280000,
    equipment: "Basic laptop, Markdown editor setup, GitHub account.",
    outcomes: "Graduates become Technical Writers capable of translating complex backend code architectures into beautiful API documentations, developer user guides, and SDK manuals."
  },
  {
    id: "c-17",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "AI Prompt Engineering & Workflow Automation",
    description: "Students transform into AI Solutions Engineers who build custom business LLM chatbots, fine-tune context parameters, and embed autonomous agents into daily workflows.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 6,
    modules: ["Week 1-2: Zero-shot & Few-shot prompt topologies", "Week 3: Context window design & LLM API connections", "Week 4-5: Building business chatbots (Google AI Studio / OpenAI)", "Week 6: Creating autonomous software tasks with AI"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 180000,
    pricingBeginner: 100000,
    pricingIntermediate: 180000,
    pricingExpert: 300000,
    equipment: "Laptop, access to LLM developer environments (Google AI Studio, OpenAI API).",
    outcomes: "Students transform into AI Solutions Engineers who build custom business LLM chatbots, fine-tune context parameters, and embed autonomous agents into daily workflows."
  },
  {
    id: "c-18",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Blockchain & Smart Contract Development",
    description: "Graduates become Web3 Engineers capable of programming secure Solidity smart contracts, auditing protocol logic, and launching functional decentralized apps.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 14,
    modules: ["Week 1-4: Web3 Cryptographic Models & EVM architectures", "Week 5-8: Programming secure Smart contracts (Solidity / Remix IDE)", "Week 9-11: Testing smart contracts & Web3 Frontends connection", "Week 12-14: Contracts Deployment, Audits & Gas Optimization"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 500000,
    pricingBeginner: 300000,
    pricingIntermediate: 500000,
    pricingExpert: 900000,
    equipment: "8GB RAM Laptop, VS Code, Remix IDE access.",
    outcomes: "Graduates become Web3 Engineers capable of programming secure Solidity smart contracts, auditing protocol logic, and launching functional decentralized apps."
  },
  {
    id: "c-19",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Sales Funnel Engineering & Email Marketing",
    description: "Students become Funnel Architects who design high-converting checkout sequences, build automated lead-capture pages, and write profitable email loops.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 6,
    modules: ["Week 1-2: Cart Checkout design & conversions optimizations", "Week 3-4: Dynamic Landing Pages & Opt-ins engineering", "Week 5: Email marketing systems wiring (Klaviyo / Mailchimp)", "Week 6: Analytics configurations, A/B testing & CRM ties"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 160000,
    pricingBeginner: 100000,
    pricingIntermediate: 160000,
    pricingExpert: 250000,
    equipment: "Laptop, testing sandboxes for email marketing systems (Klaviyo, Mailchimp).",
    outcomes: "Students become Funnel Architects who design high-converting checkout sequences, build automated lead-capture pages, and write profitable email loops."
  },
  {
    id: "c-20",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Executive Virtual Assistance (VA Mastery)",
    description: "Graduates become Executive VAs skilled in complex calendar scheduling, data management, global project handling, and executive inbox zero frameworks.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 6,
    modules: ["Week 1-2: Dynamic Calendar Management & Timezonings", "Week 3: Inbox triage setups & automated filtering rules", "Week 4-5: Google Workspace Master setups & projects layouts", "Week 6: Freelance VA systems setup & Client acquisition"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 100000,
    pricingBeginner: 60005,
    pricingIntermediate: 100000,
    pricingExpert: 180000,
    equipment: "Reliable laptop, crisp microphone headset, Google Workspace master setup.",
    outcomes: "Graduates become Executive VAs skilled in complex calendar scheduling, data management, global project handling, and executive inbox zero frameworks."
  },
  {
    id: "c-21",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Video Editing & Motion Graphics",
    description: "Students graduate as Video Editors who cut commercial clips, design dynamic text motion sequences, color grade video log formats, and engineer crisp audio tracks.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 10,
    modules: ["Week 1-3: Timeline setups, Cuts & Sequences assembly", "Week 4-5: Creating dynamic transition motion graphics in After Effects", "Week 6-8: Pro Audio mixings & Color Grading logs", "Week 9-10: Client specs creations, rendering optimization & exports"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 220000,
    pricingBeginner: 120000,
    pricingIntermediate: 220000,
    pricingExpert: 350000,
    equipment: "Dedicated GPU Laptop (8GB+ RAM), Adobe Premiere Pro, After Effects.",
    outcomes: "Students graduate as Video Editors who cut commercial clips, design dynamic text motion sequences, color grade video log formats, and engineer crisp audio tracks."
  },
  {
    id: "c-22",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "3D Animation & Character Modeling",
    description: "Graduates break out as 3D Animators who sculpt high-resolution organic meshes, build mechanical rigging models, and render physics-based promotional scenes.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 12,
    modules: ["Week 1-3: Blender viewport masteries & mesh sculpts", "Week 4-6: Spatial UV mapping & realistic materials mapping", "Week 7-9: Skeletal bone rigs, rigging & vertex weighting", "Week 10-12: Timelines keyframings & volumetric rendering engines"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 300000,
    pricingBeginner: 150000,
    pricingIntermediate: 300000,
    pricingExpert: 500000,
    equipment: "Dedicated Graphics Card Laptop (16GB RAM), Blender software client.",
    outcomes: "Graduates break out as 3D Animators who sculpt high-resolution organic meshes, build mechanical rigging models, and render physics-based promotional scenes."
  },
  {
    id: "c-23",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "E-commerce Management & Store Engineering",
    description: "Students become E-commerce Operations Managers who design high-converting digital storefronts, manage inventory flows, and run automated logistics setups.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Shopify Store themes setups & Customizations", "Week 3-4: Inventories configurations & Suppliers syncs", "Week 5-6: Logistics, dropshipping & checkout gateways integrations", "Week 7-8: Funnel layouts & Customer conversion ads loops"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 160000,
    pricingBeginner: 100000,
    pricingIntermediate: 160000,
    pricingExpert: 250000,
    equipment: "Laptop, access to staging sandbox frameworks for Shopify and WooCommerce.",
    outcomes: "Students become E-commerce Operations Managers who design high-converting digital storefronts, manage inventory flows, and run automated logistics setups."
  },
  {
    id: "c-24",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Forex & Smart Money Concepts (SMC) Trading",
    description: "Graduates operate as Independent Institutional Traders who accurately identify algorithmic market liquidity structures, read real price actions, and manage risk capital portfolios.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 12,
    modules: ["Week 1-3: Market liquidity structures & Order blocks", "Week 4-6: Premium discount lines, Fair value gaps mappings", "Week 7-9: Multi-timeframes analysis & Entry models with TradingView", "Week 10-12: Strict risk calculations, draws & psychological systems"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 220000,
    pricingBeginner: 120000,
    pricingIntermediate: 220000,
    pricingExpert: 400000,
    equipment: "Laptop or responsive tablet device, TradingView charting terminal.",
    outcomes: "Graduates operate as Independent Institutional Traders who accurately identify algorithmic market liquidity structures, read real price actions, and manage risk capital portfolios."
  },
  {
    id: "c-25",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "CRM Platform Administration",
    description: "Students transform into CRM Enterprise Admins who build clean corporate custom pipelines, manage cross-department user access systems, and deploy multi-tiered sales automations.",
    category: "Digital Course",
    level: "Intermediate",
    durationWeeks: 10,
    modules: ["Week 1-3: Hubspot Hub mappings & Custom Fields design", "Week 4-5: Multi-tiered Deal pipelines setups & routing systems", "Week 6-8: Sales workflow automations & notifications triggers", "Week 9-10: Cross-department permissions & executives metrics reports"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 300000,
    pricingBeginner: 150000,
    pricingIntermediate: 300000,
    pricingExpert: 550000,
    equipment: "Laptop, access to HubSpot Academy or Salesforce sandbox testing environments.",
    outcomes: "Students transform into CRM Enterprise Admins who build clean corporate custom pipelines, manage cross-department user access systems, and deploy multi-tiered sales automations."
  },
  {
    id: "c-26",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Advanced Fashion Design & Haute Couture",
    description: "Students graduate as Professional Fashion Designers capable of taking custom body measurements, drafting complex patterns, cutting fabric with precision, and fully sewing bespoke and bridal garments.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 16,
    modules: ["Week 1-4: Standard body metrics & complex Pattern designs", "Week 5-8: Precision fabrics cutting & sewing techniques", "Week 9-12: Bespoke gown designs & structured corsetcries", "Week 13-16: Haute Couture bridal finishes & collections launching"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 350000,
    pricingBeginner: 150000,
    pricingIntermediate: 350000,
    pricingExpert: 800000,
    equipment: "Manual or electric sewing machine, pattern papers, tailoring shears, measuring tapes, and dress forms.",
    outcomes: "Students graduate as Professional Fashion Designers capable of taking custom body measurements, drafting complex patterns, cutting fabric with precision, and fully sewing bespoke and bridal garments."
  },
  {
    id: "c-27",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Professional Wig Making & Bridal Hair Styling",
    description: "Graduates become Elite Hair Stylists and Wig Consultants who can construct custom lace wigs from scratch, perform flawless ventilation, blend extensions, and execute advanced bridal styling techniques.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Lace caps sizing & structures, ventilations", "Week 3-4: Wig creation from scratch (human hair tracks assembly)", "Week 5-6: Lace styling, bleachings, plucking, and custom tinting", "Week 7-8: Bridal up-dos styling, extensions blending and styling"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 150000,
    pricingBeginner: 80000,
    pricingIntermediate: 150000,
    pricingExpert: 300000,
    equipment: "Mannequin head and stand, lace frontals/closures, human hair bundles, ventilation needles, and high-heat styling irons.",
    outcomes: "Graduates become Elite Hair Stylists and Wig Consultants who can construct custom lace wigs from scratch, perform flawless ventilation, blend extensions, and execute advanced bridal styling techniques."
  },
  {
    id: "c-28",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Professional Makeup Artistry (Gele, Bridal & Editorial)",
    description: "Students graduate as Certified Makeup Artists capable of identifying skin types, applying flawless skin-like foundations, shaping eyebrows, tying advanced Gele styles, and designing editorial looks.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Derm profiling, brow mappings & foundations matches", "Week 3-4: Flawless skin work & glamorous bridal eyeshadow styles", "Week 5-6: Gele tying techniques (Advanced pleated Gele, bridal styles)", "Week 7-8: Editorial looks design & photo-studio lightning calibrations"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 130000,
    pricingBeginner: 70000,
    pricingIntermediate: 130000,
    pricingExpert: 250000,
    equipment: "Professional makeup vanity kit (foundations, concealers, palettes), sanitization sets, and multi-style Gele fabrics.",
    outcomes: "Students graduate as Certified Makeup Artists capable of identifying skin types, applying flawless skin-like foundations, shaping eyebrows, tying advanced Gele styles, and designing editorial looks."
  },
  {
    id: "c-29",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Commercial Videography & Lighting Tech",
    description: "Graduates become Commercial Directors and Cinematographers who can manually operate high-end cameras, design professional three-point lighting setups, and capture crisp live-production audio.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 10,
    modules: ["Week 1-3: DSLR manual setups, lens focal points audits", "Week 4-5: Audio captures, lavaliers configurations & booms", "Week 6-8: Professional 3-Point lighting (Key, Fill, Back light mappings)", "Week 9-10: On-field directing protocols & fast motion shot loops"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 250000,
    pricingBeginner: 120000,
    pricingIntermediate: 250000,
    pricingExpert: 450000,
    equipment: "DSLR or Mirrorless Camera, 50mm/secondary zoom lenses, LED continuous lights, wireless lavalier microphones, and camera gimbals.",
    outcomes: "Graduates become Commercial Directors and Cinematographers who can manually operate high-end cameras, design professional three-point lighting setups, and capture crisp live-production audio."
  },
  {
    id: "c-30",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Commercial Poultry Farming & Management",
    description: "Students become Poultry Farm Managers capable of designing biosecurity frameworks, managing brooding cycles, diagnosing common avian diseases, and optimizing feed-to-meat conversion ratios.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Brooder layouts, brooding cycles & temp settings", "Week 3-4: Strategic nutrition, formulations & feed ratios scaling", "Week 5-6: Disease tracking, vaccinations & biosecurity protocols", "Week 7-8: Farm scales accounting & logistics optimization"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 140000,
    pricingBeginner: 60000,
    pricingIntermediate: 140000,
    pricingExpert: 300000,
    equipment: "Brooder boxes, feeding/watering troughs, industrial weighing scales, thermometers, and introductory medication kits.",
    outcomes: "Students become Poultry Farm Managers capable of designing biosecurity frameworks, managing brooding cycles, diagnosing common avian diseases, and optimizing feed-to-meat conversion ratios."
  },
  {
    id: "c-31",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Animal Husbandry (Piggery & Cattle Rearing)",
    description: "Graduates operate as Livestock Production Specialists skilled in managing breeding selection, constructing optimal animal pens, formulating nutritional feed blocks, and implementing routine veterinary care.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 10,
    modules: ["Week 1-3: Pens structural design, waste drainage routing", "Week 4-5: Breed selectors, genetical optimizations & gestations", "Week 6-8: Nutritional feeding blocks composition & vet cares", "Week 9-10: Commercial sales scaling & health logs metrics"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 180000,
    pricingBeginner: 80000,
    pricingIntermediate: 180000,
    pricingExpert: 350000,
    equipment: "Feeding troughs, protective rubber boots, weighing hooks, ear-notching tools, and basic veterinary syringes.",
    outcomes: "Graduates operate as Livestock Production Specialists skilled in managing breeding selection, constructing optimal animal pens, formulating nutritional feed blocks, and implementing routine veterinary care."
  },
  {
    id: "c-32",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Modern Aquaculture & Fish Farm Engineering",
    description: "Students transform into Aquaculture Consultants who can design earthen, concrete, and tarpaulin ponds, manage complex water testing metrics, and safely run fish breeding (stripping) operations.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Ponds structural layouts (Concrete / Tarpaulins grids)", "Week 3-4: Water pH testing, aerations & filtration systems", "Week 5-6: Fingerlings stocking & strategic feeding conversions", "Week 7-8: Fish stripping (advanced breeding) & hatching workflows"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 120000,
    pricingBeginner: 60000,
    pricingIntermediate: 120000,
    pricingExpert: 250000,
    equipment: "Tarpaulin or plastic test tanks, water pH testing meters, dissolved oxygen test kits, water pumps, and spawning tools.",
    outcomes: "Students transform into Aquaculture Consultants who can design earthen, concrete, and tarpaulin ponds, manage complex water testing metrics, and safely run fish breeding (stripping) operations."
  },
  {
    id: "c-33",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Hydroponics & Greenhouse Farming Systems",
    description: "Graduates become Soilless Farming Technicians capable of plumbing horizontal and vertical hydroponic systems, mixing exact nutrient solutions, and managing microclimates inside modern greenhouses.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: NFT & DWC channels layout setups & water flows", "Week 3-4: Precision EC measurements & nutrient solutions mixers", "Week 5-6: Microclimate gauges & relative cooling controls", "Week 7-8: Crop selections, diagnostics & yield recordings"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 220000,
    pricingBeginner: 100000,
    pricingIntermediate: 220000,
    pricingExpert: 400000,
    equipment: "PVC pipes and channels, submersible water pumps, nutrient EC (Electrical Conductivity) meters, rockwool growth media, and pH adjustments.",
    outcomes: "Graduates become Soilless Farming Technicians capable of plumbing horizontal and vertical hydroponic systems, mixing exact nutrient solutions, and managing microclimates inside modern greenhouses."
  },
  {
    id: "c-34",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Professional Pest Control & Fumigation Tech",
    description: "Students graduate as Licensed Pest Control Officers who can safely identify domestic and industrial insect infestations, calibrate exact chemical mixing ratios, and operate specialized motorized treatment equipment.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 6,
    modules: ["Week 1-2: Vector tracking & insect identification guidelines", "Week 3-4: Precision Chemical calibrations & mixing protocols", "Week 5: Operating motorized knapsack sprayers & thermal foggers", "Week 6: Safety, PPE management & commercial contract rules"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 110000,
    pricingBeginner: 50000,
    pricingIntermediate: 110000,
    pricingExpert: 200000,
    equipment: "Motorized knapsack sprayers, thermal fogging machines, personal protective equipment (respirator masks, hazard suits), and chemical measuring flasks.",
    outcomes: "Students graduate as Licensed Pest Control Officers who can safely identify domestic and industrial insect infestations, calibrate exact chemical mixing ratios, and operate specialized motorized treatment equipment."
  },
  {
    id: "c-35",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Inverter & Solar Power System Installation",
    description: "Graduates become Solar Energy Engineers capable of conducting household load audits, mapping solar panel arrays, wiring inverter battery banks, and troubleshooting system faults.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Household electrical load audits & sizing rules", "Week 3-4: Solar panels arrays mapping, angles, brackets, and solar pathfinders", "Week 5-6: Inverter wiring, batteries bank configuration & safety fuses", "Week 7-8: Troubleshooting charge controllers & testing systems"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 150000,
    pricingBeginner: 70000,
    pricingIntermediate: 150000,
    pricingExpert: 300000,
    equipment: "Digital multimeters, solar panels, deep-cycle testing batteries, charge controllers, wire strippers, and industrial crimping tools.",
    outcomes: "Graduates become Solar Energy Engineers capable of conducting household load audits, mapping solar panel arrays, wiring inverter battery banks, and troubleshooting system faults."
  },
  {
    id: "c-36",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "CCTV & Smart Home Security Installation",
    description: "Students transform into Security Systems Installers who can terminate coaxial and network cables, map IP camera configurations, deploy multi-channel DVRs/NVRs, and configure remote mobile tracking systems.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 6,
    modules: ["Week 1: Analog and IP camera layouts & lens metrics", "Week 2-3: Routing network lines, coaxial cables termination & crimping", "Week 4-5: DVR / NVR configurations & multi-channel setups", "Week 6: Static IP mapping & Remote mobile tracking configuration"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 100000,
    pricingBeginner: 50000,
    pricingIntermediate: 100000,
    pricingExpert: 180000,
    equipment: "Analog and IP security cameras, NVR/DVR boxes, BNC/RJ45 connectors, wire crimpers, and local testing screens.",
    outcomes: "Students transform into Security Systems Installers who can terminate coaxial and network cables, map IP camera configurations, deploy multi-channel DVRs/NVRs, and configure remote mobile tracking systems."
  },
  {
    id: "c-37",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Automobile Diagnostics & ECU Programming",
    description: "Graduates operate as Modern Auto Technicians capable of running OBD2 computer scans, reading diagnostic trouble codes, troubleshooting electrical wiring flaws, and flashing engine control units (ECUs).",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 12,
    modules: ["Week 1-3: OBD2 scans, error code listings & sensor readings", "Week 4-6: Electrical routing & circuit testers validation", "Week 7-9: ECU chips configurations & parameters programming", "Week 10-12: System overrides, security resets & calibrations"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 220000,
    pricingBeginner: 100000,
    pricingIntermediate: 220000,
    pricingExpert: 450000,
    equipment: "Professional OBD2 diagnostic scanners, automotive multimeters, circuit test lights, and laptop-based ECU flashing software.",
    outcomes: "Graduates operate as Modern Auto Technicians capable of running OBD2 computer scans, reading diagnostic trouble codes, troubleshooting electrical wiring flaws, and flashing engine control units (ECUs)."
  },
  {
    id: "c-38",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Interior Decoration & Spatial Design",
    description: "Students graduate as Interior Decorators who can sketch spatial room layouts, create physically balanced mood boards, source functional textiles, and style luxury residential or corporate spaces.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Floor planning, spatial dimensions & furniture grids", "Week 3-4: Color wheels, swatch matching & materials selection", "Week 5-6: Lighting layout system & luxury textiles sourcing", "Week 7-8: 3D modeling drafts & boardrooms setup presentation"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 180000,
    pricingBeginner: 80000,
    pricingIntermediate: 180000,
    pricingExpert: 400000,
    equipment: "Laser measuring tapes, color swatch wheels, basic 3D sketching apps, and fabric sample catalogs.",
    outcomes: "Students graduate as Interior Decorators who can sketch spatial room layouts, create physically balanced mood boards, source functional textiles, and style luxury residential or corporate spaces."
  },
  {
    id: "c-39",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Culinary Arts & Professional Chef Training",
    description: "Graduates become Professional Chefs skilled in global knife techniques, kitchen organization systems, exact continental recipe preparation, plating presentation, and menu pricing strategies.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 12,
    modules: ["Week 1-3: Knife handling safety, cuts & safety masteries", "Week 4-6: Continental saucings & seasoning principles", "Week 7-9: Plating geometry & complex temperature logs", "Week 10-12: Bulk kitchen economics & menu architecture design"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 300000,
    pricingBeginner: 150000,
    pricingIntermediate: 300000,
    pricingExpert: 600000,
    equipment: "Chef knife set, sharpening stones, professional uniforms, thermometers, and specialized cooking pans.",
    outcomes: "Graduates become Professional Chefs skilled in global knife techniques, kitchen organization systems, exact continental recipe preparation, plating presentation, and menu pricing strategies."
  },
  {
    id: "c-40",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Pastry, Baking & Confectionery Arts",
    description: "Students transform into Commercial Bakers capable of scaling baking recipes, crafting advanced layered wedding cakes, mastering sugar arts, and producing artisanal pastries and breads.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Dough scaling, artisan yeast mixes & ovens", "Week 3-4: Confectionery designs, layered custom cakes baking", "Week 5-6: Fondant piping techniques & sugar arts modeling", "Week 7-8: Bulk baking structures & commercial store logistics"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 140000,
    pricingBeginner: 60000,
    pricingIntermediate: 140000,
    pricingExpert: 300000,
    equipment: "Heavy-duty cake mixers, commercial baking pans, piping nozzles, digital kitchen scales, and decorating turntables.",
    outcomes: "Students transform into Commercial Bakers capable of scaling baking recipes, crafting advanced layered wedding cakes, mastering sugar arts, and producing artisanal pastries and breads."
  },
  {
    id: "c-41",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Mixology & Professional Bartending",
    description: "Graduates become Certified Mixologists who can build layered cocktails, engineer custom syrup recipes, manage bar inventory, and execute speed-pouring techniques under high-volume pressure.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 4,
    modules: ["Week 1: Glassware pairings, basic measurements & shakes", "Week 2: Advanced syrup creations & layering dynamics", "Week 3: Bar inventory controls & fast pouring styles", "Week 4: Menu designs & customer relationships layout"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 90000,
    pricingBeginner: 40000,
    pricingIntermediate: 90000,
    pricingExpert: 180000,
    equipment: "Professional cocktail shakers, strainers, bar spoons, muddlers, jiggers, and dynamic glassware sets.",
    outcomes: "Graduates become Certified Mixologists who can build layered cocktails, engineer custom syrup recipes, manage bar inventory, and execute speed-pouring techniques under high-volume pressure."
  },
  {
    id: "c-42",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Premium Furniture Making & Joinery",
    description: "Students graduate as Modern Carpentry Artisans capable of reading wood blueprints, using electric power tools, cutting structural wood joints, and applying high-gloss spraying and upholstery.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 12,
    modules: ["Week 1-3: Blueprints comprehension & wood diagnostics", "Week 4-6: Power routers calibration & joint cuts styles", "Week 7-9: Structural assembly & load checks validation", "Week 10-12: High-gloss spray finishes & modern upholstery stitching"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 200000,
    pricingBeginner: 90000,
    pricingIntermediate: 200000,
    pricingExpert: 450000,
    equipment: "Circular saws, electric routers, wood chisels, sanding machines, and pneumatic nail guns.",
    outcomes: "Students graduate as Modern Carpentry Artisans capable of reading wood blueprints, using electric power tools, cutting structural wood joints, and applying high-gloss spraying and upholstery."
  },
  {
    id: "c-43",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Aluminum Fabricating & Glass Installation",
    description: "Graduates become Structural Aluminum Fabricators capable of measuring window and door profiles, cutting aluminum extrusions safely, assembling sliding systems, and installing structural glass panels.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Profiles analysis, dimensionings & safety guidelines", "Week 3-4: Extrusions miter cuts & panel assembly lines", "Week 5-6: Sliding mechanics & airtight sealant installations", "Week 7-8: On-field installations, fittings & pressure checks"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 110000,
    pricingBeginner: 50000,
    pricingIntermediate: 110000,
    pricingExpert: 220000,
    equipment: "Aluminum miter cutting saws, glass suction lifters, punching machines, hand drills, and pop rivet guns.",
    outcomes: "Graduates become Structural Aluminum Fabricators capable of measuring window and door profiles, cutting aluminum extrusions safely, assembling sliding systems, and installing structural glass panels."
  },
  {
    id: "c-44",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Professional Photography & Studio Lighting",
    description: "Students become Studio Photographers capable of manipulating manual exposure settings, configuring professional studio flash triggers, styling models, and shooting high-end portraits.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Camera exposures systems (Apertures, Shutter-speed, ISO)", "Week 3-4: Syncing studio triggers & softbox orientations", "Week 5-6: Model posture guides and framing coordinates", "Week 7-8: Digital developments RAW files manipulations & color gradings"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 140000,
    pricingBeginner: 60000,
    pricingIntermediate: 140000,
    pricingExpert: 300000,
    equipment: "DSLR/Mirrorless Camera, studio strobe flashes, softboxes, wireless flash triggers, and backdrop systems.",
    outcomes: "Students become Studio Photographers capable of manipulating manual exposure settings, configuring professional studio flash triggers, styling models, and shooting high-end portraits."
  },
  {
    id: "c-45",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Nail Artistry & Advanced Pedicure Tech",
    description: "Graduates become Nail Technicians skilled in nail anatomy, applying seamless acrylic extensions, operating electric nail drills, drawing intricate nail art, and executing clean medical pedicures.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 4,
    modules: ["Week 1: Nail anatomies, sanitize guidelines & preppings", "Week 2: Acrylic tips application & electric drills settings", "Week 3: UV Gel systems & custom artistic designs brushes", "Week 4: Advanced medical pedicure processes & cleanups"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 70000,
    pricingBeginner: 35000,
    pricingIntermediate: 70000,
    pricingExpert: 150000,
    equipment: "UV/LED nail lamps, electric nail drills, acrylic powder kits, nail tips, gel polish collections, and pedicure tubs.",
    outcomes: "Graduates become Nail Technicians skilled in nail anatomy, applying seamless acrylic extensions, operating electric nail drills, drawing intricate nail art, and executing clean medical pedicures."
  },
  {
    id: "c-46",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Barbering & Salon Management Systems",
    description: "Students graduate as Professional Barbers capable of executing clean fades, managing skin sanitation standards, treating razor bumps, and running efficient salon systems.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 6,
    modules: ["Week 1-2: Clipper heights guidelines & clean fades mechanics", "Week 3: Razor outlining systems & beard oilings curves", "Week 4: Skin checks, treatments & sterilizer ovens", "Week 5-6: Salon CRM booking pipelines & staff reviews management"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 65000,
    pricingBeginner: 30000,
    pricingIntermediate: 65000,
    pricingExpert: 140000,
    equipment: "Professional hair clippers, trimmers, clipper guards, straight razors, sterilizers, and dynamic hair capes.",
    outcomes: "Students graduate as Professional Barbers capable of executing clean fades, managing skin sanitation standards, treating razor bumps, and running efficient salon systems."
  },
  {
    id: "c-47",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Event Planning, Stage Decor & Management",
    description: "Graduates transform into Event Designers and Coordinators capable of building production timelines, budgeting supplier vendors, handling fabric draping structures, and engineering large-scale event lighting.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: Event timetables engineering & suppliers checklists", "Week 3-4: Fabric drapes, flower panels & backdrops sizing", "Week 5-6: Dynamic spot-lighting controls & stages wiring", "Week 7-8: On-field crowd routing, vendor payouts & emergency plans"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 130000,
    pricingBeginner: 60000,
    pricingIntermediate: 130000,
    pricingExpert: 250000,
    equipment: "Structural backdrop stands, industrial fabric drapes, foam flower panels, prop tables, and basic lighting sets.",
    outcomes: "Graduates transform into Event Designers and Coordinators capable of building production timelines, budgeting supplier vendors, handling fabric draping structures, and engineering large-scale event lighting."
  },
  {
    id: "c-48",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Screen Printing & Monogramming Tech",
    description: "Students become Apparel Production Consultants who can expose mesh screens, mix textile inks, operate manual printing carousels, and configure digital monogram machines for custom branding.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 6,
    modules: ["Week 1-2: Darkrooms mesh developments & emulsion rules", "Week 3: Carousel printer settings & ink mix calculations", "Week 4-5: Multi-color aligns, drying ovens passes", "Week 6: Digital monogram printers layouts & setups"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 90000,
    pricingBeginner: 40000,
    pricingIntermediate: 90000,
    pricingExpert: 180000,
    equipment: "Printing screens, squeegees, textile plastisol inks, drying flash units, and access to a monogram machinery interface.",
    outcomes: "Students become Apparel Production Consultants who can expose mesh screens, mix textile inks, operate manual printing carousels, and configure digital monogram machines for custom branding."
  },
  {
    id: "c-49",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Wall Screeding, Painting & 3D Wallpaper Tech",
    description: "Graduates operate as Interior Finishing Technicians capable of prepping rough walls, applying ultra-smooth putty screeding coats, achieving flawless paint finishes, and measuring and sticking architectural 3D wallpapers.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 6,
    modules: ["Week 1-2: Putty screeding coats & wall sandings preps", "Week 3: Primings, alignments & painter rollers techniques", "Week 4-5: 3D pattern rolls measurements & adhesive paste brushes", "Week 6: Quality visual checks, bubbles checks & trim cutouts"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 80000,
    pricingBeginner: 35000,
    pricingIntermediate: 80000,
    pricingExpert: 160000,
    equipment: "Screeding trowels, paint rollers and extension poles, sandpaper holders, spirit levels, and wallpaper adhesive brushes.",
    outcomes: "Graduates operate as Interior Finishing Technicians capable of prepping rough walls, applying ultra-smooth putty screeding coats, achieving flawless paint finishes, and measuring and sticking architectural 3D wallpapers."
  },
  {
    id: "c-50",
    trainerId: "u-admin-1",
    trainerName: "Sabicrest Academy",
    title: "Skin Care Formulation & Aesthetic Science",
    description: "Students transform into Cosmetic Formulators who understand ingredient pH levels, safely calculate batch percentages, formulate organic creams, soaps, and serums, and package them to meet standard regulatory guidelines.",
    category: "Physical Course",
    level: "Intermediate",
    durationWeeks: 8,
    modules: ["Week 1-2: pH ranges guides, acid profiles & balances", "Week 3-4: Oils emulsifying mixers & organic serum suspensions", "Week 5-6: Antiseptic wash creations & stabilizers controls", "Week 7-8: Regulatory labelings, packaging & batch tests logs"],
    status: "approved",
    submittedAt: "2026-06-01T08:00:00Z",
    approvedAt: "2026-06-01T08:00:00Z",
    price: 180000,
    pricingBeginner: 80000,
    pricingIntermediate: 180000,
    pricingExpert: 400000,
    equipment: "Digital micro-scales, overhead lab blenders or immersion sticks, glass beakers, pH testing strips, and clean storage containers.",
    outcomes: "Students transform into Cosmetic Formulators who understand ingredient pH levels, safely calculate batch percentages, formulate organic creams, soaps, and serums, and package them to meet standard regulatory guidelines."
  }
];
